### ISSUE TITLE
Unbounded RAM usage?

### ISSUE THREAD

**Issue by arhuaco** [CounterpartyXCP/counterparty-lib#783] opened 2015-07-08 08:17 UTC
With the recent Bitcoin SPAM DoS counterparty-server does not start. I logged RAM usage over time and it is growing linearly. Is there something that can be done?

![RAM usage of Counterparty](http://i.imgur.com/F2rP0o7.png)

I hope it's OK to report here.

**Comment by arhuaco** [comment] 2015-07-08 08:19
I mean, it starts but it is killed by the system because of OOM.

**Comment by unsystemizer** [comment] 2015-07-08 11:02
@arhuaco see https://github.com/CounterpartyXCP/counterparty-lib/issues/698
It seemed under control for a while, but it's resurfaced again. Some users are using scheduled restarts as a(n ugly) workaround.

**Comment by arhuaco** [comment] 2015-07-08 11:04
I see. For what I am doing now, this should work:

    bitcoind -minrelaytxfee=0.00005

I only generate TXs from this node and I don't use --unconfirmed.

**Comment by btcdrak** [comment] 2015-07-09 13:03
The best solution for this would be to patch bitcoind with some of @luke-jr's spam filter rules so the transaction spam attacks will not enter the mempool at all.

**Comment by adamkrellenstein** [comment] 2015-07-09 13:49
@btcdrak, I'm in favor of that. Would you apply the patch?

**Comment by robby-dermody** [comment] 2015-07-09 13:52
+1, I can apply the update to counterwallet once in. With the current setup (0.10.2 with `minrelaytxfee=0.00005`) cw01 went for about 14+ hours before bitcoind caused issues again. Hopefully this will fully resolve it.

**Comment by SlickTheNick** [comment] 2015-07-09 14:25
@robby-dermody I don't think the minrelaytxfee solution can be considered fulling resolving this. All that does is limit the lowest fees you can use on your own transactions, but more importantly this issue is going to come up again in the future when the mempool is filled with legitimate, sufficient fee paying transactions. The minrelaytxfee trick works OK for now but it doesn't change that things seem to lock up when the mempool gets too large.

**Comment by btcdrak** [comment] 2015-07-09 18:36
@adamkrellenstein I will add it when they publish the new ruleset, so it is encouraging to note that 0.00005 works while the flooding is ongoing. You can always turn it back down when they stop their attacks.

You might be interested to note some pools have ceased to mind the spam attack txs https://www.reddit.com/r/Bitcoin/comments/3cnrt8/bitfury_pool_16_of_hashrate_drops_their_max_block/csx91l1


@SlickTheNick This is a bitcoin issue, not something we can solve in Counterparty.

**Comment by SlickTheNick** [comment] 2015-07-09 18:56
@btcdrak I brought it up on #bitcoin-dev chat and it appears that its an issue specifically with the addrindex patch (@gmaxwell said they did not merge it because it has serious performance issues), nodes without it are not seeing the same effects when trying to generate transactions (I even tested this myself, normal bitcoin sends work totally fine), and it seems to specifically lock up when the "searchrawtransactions" function is called during transaction creation. Are we absolutely sure that there is nothing that could be optimized with that patch, or are we supposed to just accept the fact that we are screwed when the mempool becomes too big? That does not seem very acceptable to me over the long run.

**Comment by btcdrak** [comment] 2015-07-09 19:15
@SlickTheNick I dont like to be contradictory but my conversations with them about the patch a long time ago indicated that they had not actually tested it but generally disliked it. Greg told me the patch didnt work properly in that it returned unreliable results but was unable to point out any specifics. Real world deployment of the patch has not thrown up such errors. Bitcoin core developers were generally not keen to add addrindex only because they didnt want to "add yet another index", and want to wait to make Bitcoin Core more modular so features can be added though some kind of hooks system.

It's all very well hand waving and saying something doesnt work properly but without any examples of it, it's very hard. That was how I left the conversation now about a year ago and until we get some test cases that show addrindex is broken, I can only assume it works. 

That said, I am positive all code can be optimised but this particular issue is a direct result of transaction spam, which we have shown by rejecting many of them. Bitcoin does not gracefully handle the mempool filling yet, nor the UTXO bloating. One of the transaction "spammers" goal is specifically to drive bitcoin core to it's extremes until it breaks to force developers to tackle weaknesses.

OT: There does appear to be a potential locking issue that affects Bitcoin Core in general, there is a ticket open in Bitcoin core and I'm waiting to see the outcome of it (all upstream changes get merged into addrindex).

If there is anything that can be done to improve addrindex I will happily merge those changes, but this is already orders of magnitude better and reliable than previous solutions relying on third party software like Insight to parse and index the blockchain. addrindex has worked quite well until the "stress tests" appeared and I would remind you many many services have been falling over and breaking over the last few days because of it. Today Bitfury and F2pool, representing about 30% of the hash power have also raised their txrelay minimums so they wont even mine some of the this transaction spam now.

**Comment by adamkrellenstein** [comment] 2015-07-09 19:20
> I don't think the minrelaytxfee solution can be considered fulling resolving this. All that does is limit the lowest fees you can use on your own transactions,

@SlickTheNick, that's incorrect.

@btcdrak, re: the patch, great, thanks! I agree with your general take on the situation. (This is not a problem with Counterparty, or with your addrindex fork.) Closing the issue.

**Closed by adamkrellenstein** 2015-07-09 19:20 UTC

**Comment by adamkrellenstein** [comment] 2015-07-09 19:28
See https://github.com/CounterpartyXCP/counterparty-lib/commit/a49ae4ea797a432a64d96e282d877c00eb06f529

**Comment by SlickTheNick** [comment] 2015-07-09 19:37
@btcdrak @adamkrellenstein ok fair enough, I still think it may be worth investigating further though. If no one else is willing to, maybe il take a crack at it when I have time. but yeah, bitcoin issue so I will leave this thread as is

**Comment by adamkrellenstein** [comment] 2015-07-09 19:50
@SlickTheNick, patches are welcome! If we can reduce our memory usage (without an unreasonable increase in complexity), that'd be really good.

**Comment by btcdrak** [comment] 2015-07-09 19:56
@SlickTheNick Also I'd love a second pair of eyes over the addrindex patch, maybe get some test coverage too.

**Comment by gmaxwell** [comment] 2015-07-09 20:07
@btcdrak Sorry, thats untrue and I thought that I adequately explained that to you previously. It pains me to see you continuing to repeat misinformation.

I ran the patch for months, and found that it returned incorrect data-- e.g. zero results for utxo that were certainly in the blockchain.   I strongly suspect that it was mishandling reorganizations but I didn't spot the actual bug after brief inspection and  unfortunately I had other things to work on, -- in particular patches that didn't have the downsides of this one.   I did tell you how to reproduce the issue: leave it running on a node for a few weeks, then dump all the addresses in the UTXO and look each of them up. You'll very find missing entries.

**Comment by btcdrak** [comment] 2015-07-09 20:22
@gmaxwell Thanks for taking the time to clarify the steps to reproduce which was not clear to me in the [original discussion](https://github.com/bitcoin/bitcoin/pull/3652#issuecomment-64706828). I apologise, but I simply misunderstood. It's just from my perspective in terms of functionality, it's served our purposes reliably so far.

On a related note do you have any guidance about some specific tests that could be written that would these suspect cases? Overall I would still be very keen for addrindex to be considered for direct inclusion to Bitcoin Core if it would be acceptable in principal.

**Comment by adamkrellenstein** [comment] 2015-07-09 20:38
Let's move the discussion of the `addrindex` branch to the Bitcoin PR: https://github.com/bitcoin/bitcoin/pull/3652#issuecomment-64706828
