### ISSUE TITLE
`No information available about transaction`

### ISSUE THREAD

**Issue by arhuaco** [CounterpartyXCP/counterparty-lib#794] opened 2015-09-17 05:51 UTC
Hello there.

Running mainnet. This is the traceback after a restart to change a config setting:

```
[INFO] Resuming parsing.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/xcpm/envs/xcp/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/home/xcpm/git/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/home/xcpm/git/counterparty-cli/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/home/xcpm/git/counterparty-lib/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/home/xcpm/git/counterparty-lib/counterpartylib/lib/blocks.py", line 912, in follow
    backend.init_mempool_cache()
  File "/home/xcpm/git/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 237, in init_mempool_cache
    mempool_tx = BACKEND().getrawtransaction_batch(txhash_list, verbose=True)
  File "/home/xcpm/git/counterparty-lib/counterpartylib/lib/backend/addrindex.py", line 196, in getrawtransaction_batch
    raise BackendRPCError('{}'.format(response['error']))
counterpartylib.lib.backend.addrindex.BackendRPCError: {'code': -5, 'message': 'No information available about transaction'}
```

Thanks.
##

**Comment by adamkrellenstein** [comment] 2015-09-28 12:44
@robby-dermody, @ouziel-slama: this is still a bug in v9.51.4

**Comment by robby-dermody** [comment] 2015-09-28 12:49
Yes. That is something I fixed in the bogus-tx branch. It wasn't merged in because we'd need to look at the code more.

**Comment by adamkrellenstein** [comment] 2015-09-28 16:36
It's not any worse in v9.51.4 than v9.51.3, though, is it?

**Comment by robby-dermody** [comment] 2015-09-28 17:28
No, the same (that code is basically unchanged... If it gets a -5 error it just raises it).

**Comment by robby-dermody** [comment] 2015-09-28 17:31
Bogus tx branch seems to work well, but requires a good deal more testing before I'd be convinced that it's safe. 

(Note that it should just skip -5 results for elements in the mempool... Any element that is in a confirmed block will error on a -5... So it shouldn't ever break consensus for anything confirmed.) 

also, anything that is not a -5 error is still raised, as normal.

**Comment by rubensayshi** [comment] 2015-11-18 10:06
isn't this just transaction malleability?

**Comment by robby-dermody** [comment] 2015-11-19 21:30
@rubensayshi It could be. Do you see any other way to deal with it though besides more gracefully dealing with these -5 errors from the API?

**Comment by rubensayshi** [comment] 2015-11-20 09:47
bitcore update will make sure all signatures are low S, that should help A LOT already

**Comment by robby-dermody** [comment] 2015-11-20 13:25
did you mean "bitcoin core" instead of "bitcore" (with 0.11.1)? (bitcore I know has been upgraded as well, but that won't help here).

**Comment by robby-dermody** [comment] 2015-11-20 13:28
We can see if this problem goes away with the low S enforcement. If not, we can always merge in https://github.com/CounterpartyXCP/counterparty-lib/compare/develop...bogus_tx , which seems to work well based on some initial testing (it will just return None in the `get_raw_transactions` results for any txhash with a -5 result returned from the bitcoin API).

**Comment by rubensayshi** [comment] 2015-11-23 10:40
a transaction 'disappearing', this complaint is something I've heard plenty before and it's always malleability when I try to investigate.

I've had the same error pop up when I was testing things on testnet and reopened a wallet after a few minutes, and I was aware of some of my transactions having a high S and thus getting low S applied by the jesters who are doing constant malleability on high S signatures.

in `init_mempool_cache` I think it would require a block being found while in the process of fetching the batches of raw txs, but I guess that's possible.

I was talking about the `bitpay/bitcore-lib` update for counterwallet, afaik the old version that you guys were still using did not change a high S to a low S.

high S transactions are starting to propegate less, bitcoin core no longer relays high S as of `v0.11.1`, which ahs already reached almost 40% deployment, when you're suffering from malleability it's most likely originating from yourself ;-)

**Closed** 2024-01-17 07:48 UTC
Labels: bug
