### ISSUE TITLE
Unpack data_hex not work

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1026] opened 2018-01-31 04:54 UTC
I wanna get balances from tx_hash so i followed this tutorial

https://counterpartytalk.org/t/how-to-encode-and-decode-a-counterparty-transaction/2426

```
{
“method”: “get_tx_info”,
“params”: {“tx_hex”: “0100000001a89b03fc094f99b70d1006977280ee272f4c22b2ae2a738ed60d93fb49497e30010000006b483045022100867045c12241b097dc5e7ac873a21b2117248126aa8e7cee5982ecbe4a111a0202206ee1531937964b9c1a968a149e87b9d63a5f07fcc3eb8821a20973c2b9b6f91b0121028c661bb03d755f834a47e5d267432ae2bb002a5a63af69fd0749892fb7966c03ffffffff020000000000000000306a2e9bcaccbf7a31c1213f0b3d0c5f8b997fcdd0841d2ff3fb38a1b7dd8c2dc806222a1e74c23b9902ed7022d538ab7938f95705000000001976a914c8c934c4ad0fa394fd01747c375957f30752e26f88ac00000000”},
“jsonrpc”: “2.0”,
“id”: 1
}
```

Response:

```
{
“jsonrpc”: “2.0”,
“id”: 1,
“result”: [
“mypcUU2fYyJav7XUpPLtMVhuPupArLJtiM”,
"",
0,
6175,
“0200000000082f6b7100000000000138806f23c3c1c7d135274d267528ff3bebf311958a4776”
]
}
```

Then

```
{
“method”: “unpack”,
“params”: {“data_hex”: “0200000000082f6b7100000000000138806f23c3c1c7d135274d267528ff3bebf311958a4776”},
“jsonrpc”: “2.0”,
“id”: 1
}
```
but

```
{
“jsonrpc”: “2.0”,
“error”: {
“data”: {
“type”: “APIError”,
“message”: “unsupported message type”,
“args”: [
“unsupported message type”
]
},
“code”: -32000,
“message”: “Server error”
},
“id”: 1
}
```
Does anyone have any idea ?! , thanks

**Comment by chiguireitor** [comment] 2018-01-31 10:10
Ok, it seems you're trying to unpack an enhanced send, this should work. Will check this issue.

**Comment by longhoangwkm** [comment] 2018-02-09 01:40
@chiguireitor excuse me, how about proccessing bro

**Comment by chiguireitor** [comment] 2018-02-09 02:23
heya, sorry for the long turnaround.... been having crazy weeks after weeks.... some nice stuff coming btw. Gonna create a test case immediatly.

**Comment by longhoangwkm** [comment] 2018-02-09 02:26
@chiguireitor thanks bro, hope to see your result soon

**Comment by chiguireitor** [comment] 2018-02-09 02:41
Ok, getting same error.... inspecting

**Comment by chiguireitor** [comment] 2018-02-09 02:51
wait, my error....

**Comment by chiguireitor** [comment] 2018-02-09 03:03
Is that TX trying to send the asset "A144115188076392299"? that one doesn't exists on testnet

**Comment by chiguireitor** [comment] 2018-02-09 03:18
So, is this basically trying to decode this https://testnet.xchain.io/tx/16667 ?

Weird, it indeed is borking on the API endpoint.... gotta investigate further.

**Comment by chiguireitor** [comment] 2018-02-09 03:24
Ok, the offending code starts at https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/api.py#L764 Fix incoming soon.

**Comment by chiguireitor** [comment] 2018-02-11 18:34
Duplicate of #1018

**Closed** 2018-02-18 10:29 UTC
Labels: bug
