### ISSUE TITLE
Server error -32601: Method not found on JSON-RPC create_send

### ISSUE THREAD

**Issue by snitko** [CounterpartyXCP/counterparty-lib#734] opened 2015-03-18 16:12 UTC
When trying to do `create_send` over JSON-RPC api, I get the following error:

    Server error -32601: Method not found

At the same time, other API calls, like checking balance, do work fine.
I tried following the advice and wrapping https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/api.py#L390-L418 into

    try: 
    ... 
    except Exception as e:
       logging.exception(e)

Unfortunately, `api.log` showed no useful information about the exception. In need of assistance in discovering what's going on here and why am I getting `Server error -32601: Method not found`.

This issue is taken from the discussion here and is possibly related (although it's not clear at this point, if the same problem causes it): https://github.com/CounterpartyXCP/counterpartyd/issues/378

**Comment by adamkrellenstein** [comment] 2015-03-27 12:31
Can anyone duplicate this?

**Comment by snitko** [comment] 2015-03-28 03:55
I think it would at least be helpful if someone told me how to get the error traceback in the logs, since for now it's not even clear what causes the error. The suggested patch - adding the `try` clause - didn't log the error (which makes me think, it happens in some other place).

**Comment by adamkrellenstein** [comment] 2015-03-28 15:35
The error actually probably isn't logged at all. You just have to insert `try: except:` blocks everywhere until you find it. :/

**Comment by ouziel-slama** [comment] 2015-03-30 18:59
@snitko, did you look at the `server.log`, I think there is bug here with the logger.
You can try also to just replace `TypeError` by `Exception` here: https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/api.py#L410

**Comment by ouziel-slama** [comment] 2015-03-31 11:22
@adamkrellenstein, @robby-dermody : what do you think to rename `server.api.log` to `server.access.log`. Indeed only accesses are logged in this file, but all other messages from the API are logged directly in `server.log`: https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/api.py#L290

**Comment by adamkrellenstein** [comment] 2015-03-31 13:52
@ouziel-slama: ACK

**Comment by ouziel-slama** [comment] 2015-04-02 10:09
Done: https://github.com/CounterpartyXCP/counterpartyd/commit/864aa72f303563a21a46ed0c312843c35de2fe0c

**Comment by snitko** [comment] 2015-04-20 08:37
After updating to `9.51.0` I started to see the following output in the logs at the precise moment when I try to do `create_send` over the API:

    2015-04-20-T08:23:02+0000 [DEBUG] Getting outputs.
    2015-04-20-T08:23:02+0000 [DEBUG] Getting unconfirmed transactions.
    2015-04-20-T08:23:02+0000 [DEBUG] Checking mempool for UTXOs.
    2015-04-20-T08:23:02+0000 [DEBUG] Possible mempool UTXO: 00306f1eca9209bca42fe79533cbd55d5070237ae503651efd7760635f61addb (0/1827)
    2015-04-20-T08:23:02+0000 [DEBUG] Possible mempool UTXO: 0041f51417cb85a32d115cb5909ebe81bed8f37a8a181a175bc5c512532ff46a (1/1827)
    2015-04-20-T08:23:02+0000 [DEBUG] Possible mempool UTXO: 0057c82970839687b8d81b0a03c9aea87c048e451c6e6aef4bb94de553cf4279 (2/1827)
    2015-04-20-T08:23:02+0000 [DEBUG] Possible mempool UTXO: 00a58a68de47b536ab6f9e7497820816f1ff4a7dff1d259453b07b67d71cbfec (3/1827)
    2015-04-20-T08:23:02+0000 [DEBUG] Possible mempool UTXO: 00c2174f6b8fabf0881731d5c50bec78fa7036c0fa609a38567d3d4992b21722 (4/1827)
    2015-04-20-T08:23:02+0000 [DEBUG] Possible mempool UTXO: 00cc5b1e42a138a586e7b8c1bb326b9b3b4e438fa3c4c2536c006f77b2bc272f (5/1827)

   ...
   # goes on and on until 1827/1827
   ...

    2015-04-20-T08:23:03+0000 [DEBUG] Searching raw transactions.
    2015-04-20-T08:23:03+0000 [DEBUG] Formatting outputs.
    2015-04-20-T08:23:03+0000 [DEBUG] Pruning unspendable outputs.
    2015-04-20-T08:23:03+0000 [DEBUG] Pruning spent outputs.

Client still shows `Server error -32601`.
Does that help a bit in determining what's going on?

**Comment by ouziel-slama** [comment] 2015-04-20 10:50
@snitko: Can you please try to replace this lines: https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/api.py#L427-428 by:
```
except Exception as e: 
    logging.exception(e)
    raise APIError(str(e))
```
And tell me what error message you get, and what you see in the log ?

**Comment by snitko** [comment] 2015-04-20 21:54
@ouziel-slama 

Unfortunately no, this didn't help. However, I should probably add that there's an additional output in the logs that I previously thought was unrelated. It appears right after the line `2015-04-20-T08:23:03+0000 [DEBUG] Pruning spent outputs.`:

    2015-04-20-T21:47:40+0000 [DEBUG] Sorted UTXOs: ['amount: 0.01430392; txid: 89c3f27328635604ebd76e0e788f83a0c708ccdbe7589f48cd02d1a3bb9193a8; vout: 2; confirmations: 10487', 'amount: 0.000629; txid: 0869208b394884969997ac18f77a9c4ddb3fc5c2689f9f68cf4af4c201cf3cb9; vout: 2; confirmations: 20075', 'amount: 0.000592; txid: 0f18852ebeb3b933e65bc2c96045958012e848ca029c490d9ad3d04b75c97b29; vout: 2; confirmations: 20075', 'amount: 0.000392; txid: 5f722596e6027602406eed4b694022707595f606e30371e1a64fdb9acbe71445; vout: 2; confirmations: 20075', 'amount: 8.3e-05; txid: 43acbd291bb373e2c948b11ebb4ad1fa03f68c2e55b24a856a9062c56ea70812; vout: 2; confirmations: 33903']
    2015-04-20-T21:47:40+0000 [DEBUG] New input: amount: 0.01430392; txid: 89c3f27328635604ebd76e0e788f83a0c708ccdbe7589f48cd02d1a3bb9193a8; vout: 2; confirmations: 10487
    2015-04-20-T21:47:40+0000 [DEBUG] Change quantity: 0.01414962 BTC
    2015-04-20-T21:47:42+0000 [DEBUG] Updating mempool.

I suspect `0.01414962 BTC` is the amount of bitcoins on the address from which I'm trying to do a `create_send`. I don't know what the output means, though.

**Comment by ouziel-slama** [comment] 2015-04-21 10:26
hum.. weird.. from your logs, seems the problem happens in `transaction.construct()`. Can you please:
1) share the exact payload you are using, so I can try to reproduce
2) add a `try: ... except Exception as e: logger.exception(e)` around this lines: https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/api.py#L305-L313

**Comment by snitko** [comment] 2015-04-22 07:01
@ouziel-slama I've tried wrapping the said method in `try...except`, still nothing in the logs. I should note that `transaction.construct()` appeared to be on line 283 rather than 305, but this probably has to do with the fact that you linked me to the `master` branch which had changes since the release.

Payload? Ok, so, if I understand correctly you need the info on how much am I trying to send and which assets? It is `1 TESTCOIN`.

For the reference, here's my ruby code that constructs a JSON-RPC request:

      def send_assets(amount:, to:, from: :root, asset_name: COUNTERPARTYD_SETTINGS['asset_name'], use_pubkey: false)

        raise InvalidAmount if amount.blank? || !amount.kind_of?(Integer) || amount <= 0

        from = root_address if from == :root || from.nil?

        unsigned_tx = @@counterpartyd_rpc.create_send(
          source:      from,
          destination: to,
          asset:       asset_name,
          quantity:    amount,
          pubkey:      (use_pubkey ? pubkey_for(from) : nil),
          allow_unconfirmed_inputs: true,
        )

        signed_tx = @@counterpartyd_rpc.sign_tx(unsigned_tx_hex: unsigned_tx)
        @@counterpartyd_rpc.broadcast_tx(signed_tx_hex: signed_tx)

      end

Once again, IT DID WORK until a certain version of counterparty was released (I think it was 9.50).

**Comment by brighton36** [comment] 2015-04-27 12:58
@snitko FWIW - you may want to try using my counterparty_ruby gem in the future. I generally keep it pretty up to date, and it may save you some time. Here's what the send syntax looks like using your code as a guide: 
```ruby
      Counterparty.production!
      Counterparty::Send.new( source: from, destination: to, 
        asset: asset_name, quantity: amount, pubkey:  (use_pubkey ? pubkey_for(from) : nil), 
        allow_unconfirmed_inputs: true).save!('private-key-here')
```

**Comment by robby-dermody** [comment] 2015-11-15 15:25
@snitko Is this still an issue?

**Comment by snitko** [comment] 2015-11-15 18:37
@robby-dermody no, no longer an issue.

**Comment by robby-dermody** [comment] 2015-11-15 19:15
Great, closing.

**Closed by robby-dermody** 2015-11-15 19:15 UTC
Labels: possible bug
