### ISSUE TITLE
Not Being Able to Close A Dispenser

### ISSUE THREAD

**Issue by adilcnn** [CounterpartyXCP/counterparty-lib#1122] opened 2021-07-11 20:50 UTC
Hi,
Just got an issue with a dispenser today, already discussed on Telegram with CP channel admin, I had opened a dispenser for Pepecash with an exchange address,

34SV2dzCnVhTMJwfHnKcnMAo3DL9k4tpFo
Now I am unable to close the dispenser, it shows an error “Transaction is not an open order”. Please help me close this dispenser. Transaction hash is:

2b013e2852f54c6270799a75d81e9299df344d53ee72f95ea8f7ec1a084e195a

**Comment by adilcnn** [comment] 2021-09-11 17:50
Any update on this please, I had been given this month, so is it under process or not possible in this month as well.

**Comment by jdogresorg** [comment] 2021-09-12 14:33
No update yet. When we get some time to look into this issue and resolve it, you will be notified because additional updates will be posted here :)

**Comment by jdogresorg** [comment] 2022-02-23 17:31
You can only close a dispenser if you own the private key for that address... since you opened the dispenser on an address which is not your own (you said you opened it on an exchange address), you will be unable to close this dispenser.

The good news is that we have fixed the ability for dispensers to work with addresses that start with a 3 (p2sh), so any sends to dispensers running on p2sh addresses should dispense tokens as desired.

Your "Transaction is not an open order" error is from you trying to close an order and entering in the transaction hash of the dispenser, hence the error message about not being able to close the dispenser.

In the future please do not open dispensers on addresses that you do not full control and have the private key to sign transactions with.

**Closed by jdogresorg** 2022-02-23 17:31 UTC

**Comment by adilcnn** [comment] 2022-02-23 17:39
Sir it was you FORCEFULLY CLOSED these dispensers, if you remember our chat in Telegram, you said these will be closed now and once the issue resolved, you will reopen them, so I request you to please reopen them as these are my tokens, once the assets are recovered then you close them again. Thanks

**Comment by jdogresorg** [comment] 2022-02-23 17:44
The dispensers are open in Counterparty, they just are not displayed as open on xchain.io in order to prevent users from sending funds to these problematic dispensers.

Once we put out the new release with the 3 address dispenser fixes, then I will update xchain accordingly.

To be clear, there Is no way to manually force dispensers open and closed in Counterparty… the only way your dispenser tokens will come back to you is

1.) After we put out the 3 address dispenser fix
2.) After you send funds to the 3 address dispenser
3.) Your tokens will be sent to the address which pays for the dispense
4.) Since you do not control the 3 address (exchange address) you opened the dispenser on, you will be unable to access any BTC sent to this address.

I would STRONGLY suggest you use Counterparty as it was intended to be used and only use addresses you control the private key to and DO NOT use addresses from exchanges or which you do not control the private key to…. As your just shooting yourself in the foot cuz you will be unable to perform actions on addresses you dont own.


Jeremy Johnson
***@***.***
CoinDaddy, LLC.

**Comment by jdogresorg** [comment] 2022-02-23 20:44
I have updated all servers to 9.59.6 which contains the fix for using p2sh dispensers.

I have also updated xchain.io to remove the code which forces p2sh dispensers to appear as closed.

You should now be able to send 0.01 BTC to this dispenser and get your PEPECASH returned.
https://xchain.io/tx/2b013e2852f54c6270799a75d81e9299df344d53ee72f95ea8f7ec1a084e195a

**Comment by adilcnn** [comment] 2022-02-23 21:52
Well I sent 0.01 BTC and got the Pepecash and BTC as well, thank you so much for fixing this, really appreciate..!
