### ISSUE TITLE
dispensers - payments not detected on segwit addresses

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1074] opened 2020-03-18 03:34 UTC
It seems that payments to dispensers segwit addresses are not being detected and the dispense is not taking place.

Here is a dispenser that is setup on segwit address
https://testnet.xchain.io/tx/2d0b9536da6d19386edd35236277eb9dcfcce6af7dcc26362d76a663442d67e8

Here is a BTC payment to the segwit address which is NOT detected by the dispenser
https://blockstream.info/testnet/tx/12a3545177fd725cc71824c61486f94f3b76042fb75c99d9d37aac120784ae87

**Comment by cryptcoin-junkey** [comment] 2020-10-10 07:53
It looks the root cause is here. No care for SegWit address.

https://github.com/CounterpartyXCP/counterparty-lib/blob/558965e29e26c0c47fca2bb31f143cdf9115e8d8/counterpartylib/lib/blocks.py#L487-L489

**Comment by cryptcoin-junkey** [comment] 2020-10-10 21:16
And also no care for P2SH available... I'm going to fix it.

**Comment by cryptcoin-junkey** [comment] 2020-10-11 01:35
I make a patch against this issue for Monaparty. https://github.com/monaparty/counterparty-lib/commit/20dfef200afc7572c32c2f48d9362efff3551cb6
I'm trying on Monaparty-testnet and looks working well.

I'll port it to Counterparty and send PR if it can be acceptable.

**Comment by chiguireitor** [comment] 2020-11-06 14:21
Merged on latest commit

**Closed by chiguireitor** 2020-11-06 14:21 UTC
